const SEND_EMAIL_REQUEST = 'SEND_EMAIL_REQUEST';
const SEND_EMAIL_SUCCESS = 'SEND_EMAIL_SUCCESS';
const SERVICE_ERROR = 'SERVICE_ERROR';

const TRANSFER_MONEY = 'TRANSFER_MONEY';
const BACK_FUND_TRANFER = 'BACK_FUND_TRANFER';
const THANK_YOU_TRANSFER = 'THANK_YOU_TRANSFER';

const TEXT_TO_SPEECH_REQUEST = 'TEXT_TO_SPEECH_REQUEST';
const TEXT_TO_SPEECH_SUCCESS = 'TEXT_TO_SPEECH_SUCCESS';

const GET_TEMPRATURE_REQUEST = 'GET_TEMPRATURE_REQUEST';
const GET_TEMPRATURE_SUCCESS = 'GET_TEMPRATURE_SUCCESS';

const GET_ALL_TEMPRATURE_REQUEST = 'GET_ALL_TEMPRATURE_REQUEST';
const GET_ALL_TEMPRATURE_SUCCESS = 'GET_ALL_TEMPRATURE_SUCCESS';

const SEND_CONVERSATION_INTENT = 'SEND_CONVERSATION_INTENT';

export const actionTypes = {
  SEND_EMAIL_REQUEST,
  SEND_EMAIL_SUCCESS,
  SERVICE_ERROR,
  TRANSFER_MONEY,
  BACK_FUND_TRANFER,
  THANK_YOU_TRANSFER,

  TEXT_TO_SPEECH_REQUEST,
  TEXT_TO_SPEECH_SUCCESS,

  GET_TEMPRATURE_REQUEST,
  GET_TEMPRATURE_SUCCESS,

  GET_ALL_TEMPRATURE_REQUEST,
  GET_ALL_TEMPRATURE_SUCCESS,

  SEND_CONVERSATION_INTENT,
};
